CREATE TABLE IF NOT EXISTS attempts (
  id TEXT PRIMARY KEY,
  createdAt TEXT,
  topic TEXT,
  quiz TEXT,
  responses TEXT,
  result TEXT
);

CREATE TABLE IF NOT EXISTS nonprofits (
  id TEXT PRIMARY KEY,
  name TEXT,
  mission TEXT,
  sector TEXT,
  maturity TEXT,
  program_efficiency REAL,
  revenue_growth REAL,
  sustainability REAL,
  scale REAL,
  grant_distribution REAL,
  geographic_reach REAL,
  innovation_output REAL,
  location TEXT,
  enrichment_summary TEXT
);

CREATE TABLE IF NOT EXISTS approved_organizations (
  id TEXT PRIMARY KEY,
  nonprofit_id TEXT,
  org_ein TEXT,
  name TEXT,
  sector TEXT
);

CREATE TABLE IF NOT EXISTS organizations (
  ein TEXT PRIMARY KEY,
  name TEXT,
  state TEXT,
  region TEXT,
  sector TEXT,
  maturityTier TEXT,
  inScope INTEGER NOT NULL DEFAULT 1,
  eligibilityFlag TEXT,
  eligibilityFlagLabel TEXT,
  confidenceBand TEXT,
  missionAlignmentScore INTEGER,
  missionAlignmentRationale TEXT,
  programFocus TEXT,
  programFocusRationale TEXT,
  websiteMissionMatch TEXT,
  websiteRecentActivity TEXT,
  websiteConsistencySignal TEXT,
  websiteStatus TEXT,
  websiteUrl TEXT,
  capacityNarrative TEXT,
  missionSummary TEXT,
  primaryPrograms TEXT,
  geographicScope TEXT,
  notableSignals TEXT,
  riskSignals TEXT,
  hardRedFlags TEXT,
  softFlags TEXT,
  missionStatement TEXT,
  program1Desc TEXT,
  program2Desc TEXT,
  program3Desc TEXT,
  scheduleO TEXT,
  websiteTextExcerpt TEXT,
  scoreFinancialStability INTEGER,
  scoreRevenueHealth INTEGER,
  scoreOperationalEfficiency INTEGER,
  scoreOrganizationalMaturity INTEGER,
  scoreOverall INTEGER,
  colorFinancialStability TEXT,
  colorRevenueHealth TEXT,
  colorOperationalEfficiency TEXT,
  colorOrganizationalMaturity TEXT,
  filingContinuityRaw REAL,
  filingContinuityAdjusted REAL,
  filingContinuityAdjustedNote TEXT,
  daysCashOnHand REAL,
  monthsUnrestricted REAL,
  currentRatio REAL,
  surplusDeficit3yr TEXT,
  revenueTrend TEXT,
  revConcentrationPct REAL,
  earnedIncomePct REAL,
  programExpenseRatio REAL,
  fundraisingEfficiency REAL,
  currentRevenue REAL,
  yearsActive REAL,
  boardSize INTEGER,
  latestEmployees INTEGER
);
